(function(g){var window=this;var H3=function(a){var b={languageCode:a.u,languageName:a.w,displayName:g.oz(a),kind:a.A,name:a.B,id:a.H,is_servable:a.F,is_default:a.isDefault,is_translateable:a.isTranslateable,vss_id:a.C};a.o&&(b.translationLanguage=a.o);return b},I3=function(a){return a.o?a.o.languageCode:a.u},Oqa=function(a,b){var c=new g.nz;
c.u=a.u;c.w=a.w;c.B=a.B;c.A=a.A;c.isDefault=!1;c.F=a.F;c.isTranslateable=a.isTranslateable;c.C=a.C;c.G=a.G;c.o=b;return c},Pqa=function(){this.u=[];
this.o=[]},J3=function(a,b){return b?a.o.concat(a.u):a.o},K3=function(a,b){switch(b.A){case "asr":var c=a.u;
g.Sa(c,(0,g.x)(b.Or,b))||c.push(b);break;default:c=a.o,g.Sa(c,(0,g.x)(b.Or,b))||c.push(b)}},L3=function(a){g.A.call(this);
this.ab=a;this.u=new Pqa;this.B=[]},M3=function(a,b,c){L3.call(this,a);
this.o=null;this.B=b.Ev;this.w=c},N3=function(){this.segments=[]},O3=function(a,b,c,d,e,f){g.A.call(this);
this.M=a;this.w=b;this.O=b.P();this.B=new N3;this.o=null;this.F=d;this.J=f;this.u=this.A=null;this.S=c;this.C=e||!1;this.G=new g.L(this.Ux,1E3,this);g.B(this,this.G);this.H=new g.rr(this);g.B(this,this.H);this.H.L(b,"SEEK_COMPLETE",this.Py);this.Py();this.Ux()},Qqa=function(a,b){b-=a.w.Ab();
var c=a.o;a.o=g.Qa(a.S.Rf(b).o);c!=a.o&&a.J&&a.J()},Rqa=function(a,b){var c=g.kv(g.oy(b,a.M,{})),d={format:"RAW",
withCredentials:!0};a.C&&(d.responseType="arraybuffer");a.u=g.Tp(c,d,3,100).then((0,g.x)(a.oM,a));a.A=b;c=a.B;d=a.A.o[0].u;var e=g.kb(c.segments,d);0<=e||0>e&&1===(-e-1)%2||(e=-e-1,0<e&&1===d-c.segments[e-1]&&e<c.segments.length&&1===c.segments[e]-d?(g.Ya(c.segments,e),g.Ya(c.segments,e-1)):0<e&&1===d-c.segments[e-1]?c.segments[e-1]=d:e<c.segments.length&&1===c.segments[e]-d?c.segments[e]=d:(g.gb(c.segments,e,0,d),g.gb(c.segments,e+1,0,d)))},P3=function(a,b){L3.call(this,b.P());
this.o=a;this.F=b;this.w=null;this.A=!1;this.C=g.Vx(this.F.P())&&!this.o.u},Sqa=function(a,b){var c=[],d;
for(d in a.o.o){var e=a.o.o[d];if(g.AP(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.nz({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},Tqa=function(a,b){return null!=b&&b in a.o.o?a.o.o[b]:null},Uqa=function(a,b,c){var d=[],e;
for(e in a.o.o){var f=a.o.o[e];if(g.AP(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode==b&&d.push(f)}}return d.length?d[0]:null},Q3=function(a,b,c,d,e){L3.call(this,e||null);
c=c||g.np(a).hl||"";c=c.split("_").join("-");this.A=g.pp(a,{hl:c});this.w=b;this.C=!!d;this.F={};this.o=null},R3=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.SD.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.w=f;this.o=k},S3=function(a,b,c,d,e){g.SD.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.o=[]},T3=function(a,b){g.B(a,b);
a.o.push(b)},Vqa=function(a){a=void 0===a?{}:a;
var b="_"+U3++;return new S3(0,0x8000000000000,0,b,a)},V3=function(a,b,c,d,e,f){var k={};
g.Ma(k,b);g.Ma(k,a.params);g.Ma(k,c);var l={};g.Ma(l,b.Bb);a.params.Bb&&g.Ma(l,a.params.Bb);g.Ma(l,c.Bb);k.Bb=l;g.U.call(this,{D:"div",I:"caption-window",N:{id:"caption-window-"+a.id,dir:1==k.Od?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},K:[{D:"span",I:"captions-text",N:{style:"word-wrap: normal; display: block;"}}]});this.C=[];this.S=!1;this.w=a;this.U=this.V=null;this.Ka=e;this.Ga=f;this.F=null;this.aa=.96*e;this.wa=.96*f;this.u=k;this.Ca=c;this.B=this.o["captions-text"];this.za=
null!=this.B.style["box-decoration-break"]||null!=this.B.style["-webkit-box-decoration-break"];this.Z=d/360*16;this.type=0;this.ha=this.Z*Wqa(l);a=new g.xr(this.element,!0);g.B(this,a);a.subscribe("dragstart",this.RH,this);a.subscribe("dragmove",this.QH,this);a.subscribe("dragend",this.PH,this);this.sa=this.oa=0;b="";this.u.windowOpacity&&(a=g.D1(this.u.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.u.windowOpacity+")");a={"background-color":b,display:!1===this.u.isVisible?"none":"","text-align":Xqa[this.u.textAlign]};
this.za&&(a["border-radius"]=b?this.ha/8+"px":"");if(this.A=2==this.w.params.Od||3==this.w.params.Od)b=this.element,c="vertical-rl",1==this.u.Tt&&(c="vertical-lr"),g.Jd&&(c="vertical-lr"==c?"tb-lr":"tb-rl"),g.qh(b,"-o-writing-mode",c),g.qh(b,"-webkit-writing-mode",c),g.qh(b,"writing-mode",c),g.qh(b,"text-orientation","upright"),g.J(b,"ytp-vertical-caption"),3==this.w.params.Od&&(g.qh(b,"text-orientation",""),g.qh(b,"transform","rotate(180deg)"));g.qh(this.element,a);switch(this.u.Gf){case 0:case 1:case 2:g.J(this.element,
"ytp-caption-window-top");break;case 6:case 7:case 8:g.J(this.element,"ytp-caption-window-bottom")}},Wqa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},Yqa=function(a,b){var c={},d=b.background?b.background:a.u.Bb.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.u.Bb.backgroundOpacity;d=g.D1(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.za&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ha/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Z*Wqa(b)+"px";d=1;e=b.color||a.u.Bb.color;if(b.color||null!=b.textOpacity)e=g.D1(e),d=null==b.textOpacity?a.u.Bb.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.Xp&&(k=e=b.Xp);var l=a.Z/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),t=Math.max(5*l,1);d=[];switch(f){case 4:for(;q<=t;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(q=0;5>q;q++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.fl()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.u.Bb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Je&&(c["font-style"]="italic");
b.underline&&(c["text-decoration"]="underline");b.sF&&(c.visibility="hidden");1==b.nx&&a.A&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.Xx||g.Yx,3==a.w.params.Od?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1==b.Re||2==b.Re||3==b.Re||4==b.Re||5==b.Re)if(g.Xx)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Re){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},Zqa=function(a){a.F=g.Qd("SPAN");
g.qh(a.F,{display:"block"});g.J(a.F,"caption-visual-line");a.B.appendChild(a.F)},$qa=function(a,b){var c=g.Qd("SPAN");
g.qh(c,{display:"inline-block","white-space":"pre-wrap"});g.qh(c,Yqa(a,b));c.classList.add("ytp-caption-segment");a.F.appendChild(c);c.previousElementSibling&&(g.qh(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.qh(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},ara=function(a,b,c){a.S=a.S||!!c;
var d={};g.Ma(d,a.u.Bb);g.Ma(d,c||b.o);g.Ma(d,a.Ca.Bb);(c=!a.F)&&Zqa(a);for(var e=a.V&&a.U&&g.Xb(d,a.U)?a.V:$qa(a,d),f="string"===typeof b.text,k=f?b.text.split("\n"):[b.text],l=0;l<k.length;l++){var m=0<l||!b.w,n=k[l];m&&!c?(Zqa(a),e=$qa(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Rd(n):n),f||"RUBY"!=n.tagName||4!=n.childElementCount||g.Xx||!g.uh(n.children[2],"text-emphasis")||(m=a.A?"padding-right":"padding-top",g.uh(n.children[2],"text-emphasis-position")&&(m=a.A?"padding-left":"padding-bottom"),
g.Ld?g.qh(e,m,"1em"):g.qh(e,m,"0.5em")))}a.U=d;a.V=e;a.C.push(b)},bra=function(){},X3=function(){this.A=this.u=this.mode=this.w=0;
this.B=new W3(this);this.C=new W3(this);this.o=[];this.clear()},dra=function(a,b,c){if(255==a&&255==b||!a&&!b)return{rm:a,
sm:b,result:0};a=cra[a];b=cra[b];if(a&128){if(!(b&128)&&0!=c.o&&c.u==b)return{rm:a,sm:b,result:1}}else if(b&128&&1<=a&&31>=a)return{rm:a,sm:b,result:2};return{rm:a,sm:b,result:3}},fra=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.A&&a.reset(),a.B.o.clear(),a.C.o.clear()):(a.A=0,era(a.B,b,c,d))},gra=function(a,b){a.o.sort(function(e,f){var k=e.time-f.time;
return 0==k?e.order-f.order:k});
for(var c=0;c<a.o.length;c++){var d=a.o[c];a.u=d.time;0==d.type?fra(a,d.Gv,d.Hv,b):1==d.type&&a.w&496&&era(a.C,d.Gv,d.Hv,b)}a.o.length=0},Y3=function(){this.o=0},Z3=function(){this.u=this.w=this.o=0},$3=function(){this.timestamp=this.le=0},a4=function(a){this.w=[];
for(var b=0;15>=b;b++){this.w[b]=[];for(var c=0;32>=c;c++)this.w[b][c]=new $3}this.o=this.u=this.row=0;this.style=new Y3;this.B=a;this.A=0},b4=function(a,b){if(3==a.style.o){for(var c=0,d=0,e=a.B.u+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var t=a.w[m][q];
if(0!=t.le){0==c&&(c=m,d=q);n=String.fromCharCode(t.le);var u=t.timestamp;u<e&&(e=u);t.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==t.le||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.B.u+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.w[k][m],t=q.le,0!=t&&(0==c&&(c=k,d=m),n=String.fromCharCode(t),u=q.timestamp,u<=e&&(e=u),l+=n,q.reset()),32==m||0==t)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},lra=function(a,b){switch(a){case 0:return hra[(b&127)-32];
case 1:return ira[b&15];case 2:return jra[b&31];case 3:return kra[b&31]}return 0},c4=function(a){return a.w[a.row][a.u]},d4=function(a,b,c){2<=b&&1<a.u&&(--a.u,c4(a).le=0);
var d=c4(a);d.timestamp=a.B.u+0;d.le=lra(b,c);32>a.u&&a.u++},mra=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.w[b+e][f].xg(a.w[c+e][f])},e4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.w[b+d][e].reset()},f4=function(a){a.row=0<a.o?a.o:1;
a.u=1;e4(a,0,15)},g4=function(a){this.A=a;
this.B=0;this.style=new Y3;this.C=new a4(a);this.F=new a4(a);this.G=new a4(a);this.u=this.C;this.w=this.F;this.o=this.u},h4=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:if(0<d.o)break;case 1:case 2:b4(d,c),f4(a.u),f4(a.w),d.row=15,d.o=b,e=!0}a.style.set(3);a.o=d;a.o.style=a.style;a.A.mode=1<<d.A;e?d.u=1:d.o!=b&&(d.o>b?(b4(d,c),e4(d,d.row-d.o,b)):d.row<b&&(b=d.o),d.o=b)},nra=function(a){a.style.set(1);
a.o=a.w;a.o.o=0;a.o.style=a.style;a.A.mode=1<<a.o.A},ora=function(a){a.style.set(4);
a.o=a.G;a.o.style=a.style;a.A.mode=1<<a.o.A},W3=function(a){this.u=a;
this.o=new Z3;this.B=0;this.w=new g4(a);this.C=new g4(a);this.A=this.w},era=function(a,b,c,d){a.o.update();
b=dra(b,c,a.o);switch(b.result){case 0:return;case 1:case 2:return}var e=b.rm;c=b.sm;if(32<=e||!e)a.u.mode&a.u.w&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.A.o,b&96&&d4(a,0,b),c&96&&d4(a,0,c),0!=b&&0!=c&&3==a.style.o&&b4(a,d));else if(e&16)a:if(!a.o.matches(e,c)&&(b=a.o,b.w=e,b.u=c,b.o=2,b=e&8?a.C:a.w,a.A=b,a.u.mode=1<<(a.B<<2)+(b.B<<1)+(4==b.style.o?1:0),(a.u.mode|1<<(a.B<<2)+(b.B<<1)+(4!=b.style.o?1:0))&a.u.w))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.o;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.o&&(d=c.o,d==c.row))break;var f=1+c.row-c.o,k=1+d-c.o;mra(c,k,f,c.o);b=f;e=c.o;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));e4(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:d4(b.o,0,32);break a;case 48:57==c?(d=b.o,c4(d).le=0,32>d.u&&d.u++):d4(b.o,1,c&15)}break;case 2:c&32&&d4(b.o,2,c&31);break;case 3:c&32&&d4(b.o,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:nra(b);break;
case 33:d=b.o;1<d.u&&(--d.u,c4(d).le=0);break;case 36:d=b.o;b=c4(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.w[a][c]==b){for(;32>=c;c++)d.w[a][c].reset();break}break;case 37:h4(b,2,d);break;case 38:h4(b,3,d);break;case 39:h4(b,4,d);break;case 40:d4(b.o,0,32);break;case 41:b.style.set(2);b.o=b.u;b.o.o=0;b.o.style=b.style;b.A.mode=1<<b.o.A;break;case 42:d=b.G;d.o=15;d.style.set(4);f4(d);ora(b);break;case 43:ora(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:b4(a,d)}e4(a,0,15);break;
case 45:b:{a=b.o;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.o&&(a.o=2,a.row<a.o&&(a.row=a.o));b=a.row-a.o+1;b4(a,d);mra(a,b,b+1,a.o-1);e4(a,a.row,1)}break;case 46:e4(b.w,0,15);break;case 47:b4(b.u,d),b.w.updateTime(b.A.u+0),d=b.w,b.w=b.u,b.u=d,nra(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.o,32<(d.u+=c&3)&&(d.u=32)}}},qra=function(a,b,c,d,e,f,k){var l=f[0],m=k[l.getAttribute("p")];
if(1==m.Mb){var n=f[1],q=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");q.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");k=k[q.getAttribute("p")];l=pra(l.textContent,n.textContent,q.textContent,f.textContent,k);return new R3(a,b,e,c,l,d,m)}switch(m.Mb){case 9:case 10:m.Re=1;break;case 11:m.Re=2;break;case 12:m.Re=3;break;case 13:m.Re=4;break;case 14:m.Re=5}return new R3(a,b,e,c,l.textContent||"",d,m)},pra=function(a,b,c,d,e){var f=g.fl(),k=f?
g.Qd("DIV"):g.Qd("RUBY"),l=g.Qd("SPAN");
l.textContent=a;k.appendChild(l);a=f?g.Qd("DIV"):g.Qd("RP");a.textContent=b;k.appendChild(a);b=f?g.Qd("DIV"):g.Qd("RT");b.textContent=c;k.appendChild(b);c=e.Mb;if(10==c||11==c||12==c||13==c||14==c)if(g.qh(b,"text-emphasis-style","filled circle"),g.qh(b,"text-emphasis-color","currentcolor"),g.qh(b,"webkit-text-emphasis","filled circle"),e.Mb==e.Mb==11||13==e.Mb)g.qh(b,"webkit-text-emphasis-position","under left"),g.qh(b,"text-emphasis-position","under left");c=!0;if(4==e.Mb||7==e.Mb||12==e.Mb||14==
e.Mb)g.qh(k,"ruby-position","over"),g.qh(k,"-webkit-ruby-position","before");else if(5==e.Mb||6==e.Mb||11==e.Mb||13==e.Mb)g.qh(k,"ruby-position","under"),g.qh(k,"-webkit-ruby-position","after"),c=!1;e=f?g.Qd("DIV"):g.Qd("RP");e.textContent=d;k.appendChild(e);f&&(d=c,g.qh(k,{display:"inline-block",position:"relative"}),f=k.firstElementChild.nextElementSibling,g.qh(f,"display","none"),f=f.nextElementSibling,g.qh(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.qh(k.lastElementChild,"display","none"),d?(g.qh(k,"padding-top","0.6em"),g.qh(f,"top","0")):(g.qh(k,"padding-bottom","0.6em"),g.qh(f,"bottom","0")));return k},i4=function(){g.A.apply(this,arguments)},j4=function(a){i4.call(this);
this.A={};this.H={};this.M={};this.B="_"+U3++;this.C=a;this.G={};this.u=this.o=null;this.F=!0},k4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return parseFloat(c)},l4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},m4=function(a,b){var c=k4(a,b);
return void 0!=c?c:null},o4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return n4.test(c),c},rra=function(a,b){var c={},d=b.getAttribute("ws");
g.Ma(c,d?a.M[d]:a.C);d=m4(b,"mh");null!=d&&(c.aj=d);d=m4(b,"ju");null!=d&&(c.textAlign=d);d=m4(b,"pd");null!=d&&(c.Od=d);d=m4(b,"sd");null!=d&&(c.Tt=d);d=o4(b,"wfc");null!=d&&(c.windowColor=d);d=k4(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},sra=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ma(c,a.H[d]);d=m4(b,"ap");null!=d&&(c.Gf=d);d=k4(b,"cc");null!=d&&(c.vg=d);d=k4(b,"ah");null!=d&&(c.Ke=d);d=k4(b,"rc");null!=d&&(c.lg=d);d=k4(b,"av");null!=d&&(c.mg=d);return c},tra=function(a,b,c,d){var e={};
g.Ma(e,sra(a,b));g.Ma(e,rra(a,b));d?g.Xb(e,a.C)?(d=a.B,e=a.C):d="_"+U3++:d=b.getAttribute("id")||"_"+U3++;a=k4(b,"t")+c;b=k4(b,"d")||0x8000000000000;if(2==e.Od||3==e.Od)c=e.lg,e.lg=e.vg,e.vg=c;return new S3(a,b,0,d,e)},p4=function(a){i4.call(this);
this.o=new Map;this.A=new Map;this.B=new Map;this.u=new Map;this.C=a},q4=function(a){a=g.nd(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},ura=function(a,b,c,d,e){0==d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.A.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.B.get(b.wsWinStyleId));a=b.rcRowCount;void 0!=a&&(f.lg=a);b=b.ccColCount;void 0!=b&&(f.vg=b);if(2===f.Od||3===f.Od)b=f.lg,f.lg=f.vg,f.vg=b;return new S3(c,d,0,e,f)},r4=function(a,b,c,d,e,f,k){V3.call(this,a,b,c,d,e,f,k);
this.type=1},s4=function(a,b,c){this.F=c;
this.version=this.C=this.A=this.o=0;this.u=new DataView(a);this.w=[]},t4=function(a){var b=a.o;
a.o+=1;return a.u.getUint8(b)},u4=function(a){var b=a.o;
a.o+=4;return a.u.getUint32(b)},v4=function(a,b){i4.call(this);
this.u=a;this.track="CC3"==b.w?4:0;this.o=new X3;this.o.w=1<<this.track},wra=function(a){if("string"===typeof a)return!1;
a=new s4(a,8,0);return vra(a)},vra=function(a){if(!(a.o<a.u.byteLength)||1380139777!=u4(a))return!1;
a.version=t4(a);if(1<a.version)return!1;t4(a);t4(a);t4(a);return!0},w4=function(a,b,c,d,e,f,k){V3.call(this,a,b,c,d,e,f,k);
g.J(this.element,"ytp-caption-window-rollup");this.type=2;this.G=[];this.J=this.H=this.da=0;this.O=NaN;this.ya=0;this.Aa=null;this.ea=new g.L(this.tM,433,this);g.B(this,this.ea);g.qh(this.element,"overflow","hidden")},xra=function(a,b){return(a.A?b.offsetHeight:b.offsetWidth)+1},yra=function(a){if(isNaN(a.O)){var b=a.u.vg;
if(b){var c=g.Qd("SPAN");g.$d(c,"\u2013".repeat(b));g.qh(c,Yqa(a,a.u.Bb));a.B.appendChild(c);a.O=c.offsetWidth;a.B.removeChild(c)}else a.O=0}return a.O},zra=function(a,b){if(!b)return"";
a.A&&1!=a.w.params.Tt&&(b*=-1);return"translate"+(a.A?"X":"Y")+"("+b+"px)"},Ara=function(a){a.G=[].concat(g.ea(document.getElementsByClassName("caption-visual-line")));
for(var b=a.w.params.lg,c=0,d=0,e=a.G.length-1;c<b&&-1<e;){var f=a.G[e];d+=a.A?f.offsetWidth:f.offsetHeight;c++;e--}a.G.length<b&&(d*=b/a.G.length);a.H=d;a.J=Math.max(yra(a),a.ya,xra(a,a.B))},Bra=function(a,b){Ara(a);
var c=a.G.reduce(function(e,f){return(a.A?f.offsetWidth:f.offsetHeight)+e},0);
c=a.H-c;if(c!=a.da){var d=0<c&&0==a.da;b||isNaN(c)||d||(g.J(a.element,"ytp-rollup-mode"),g.Qn(a.ea));g.qh(a.B,"transform",zra(a,c));a.da=c}Ara(a)},x4=function(){i4.call(this)},Cra=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Je=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType)q=new R3(b,c,d,e.id,q.nodeValue,f||0<n,g.Vb(l)?void 0:l),m.push(q),T3(e,q);else{var t={};g.Ma(t,l);Cra(a,b,c,d,e,!0,q,t,m)}}},y4=function(a){var b=a.split(":");
a=0;b=g.p(b);for(var c=b.next();!c.done;c=b.next())a=60*a+parseFloat(c.value);return 1E3*a},Dra=function(a,b,c,d){d=Object.assign({aj:0},d);
return new S3(a,b,c,"_"+U3++,d)},z4=function(a){g.A.call(this);
this.u=a;this.o=null},Fra=function(a){var b={};
if(a=I3(a))b.lang=a,Era.test(a)&&(b.Od=1);return b},C4=function(a){g.zP.call(this,a);
this.w=a.P();this.T=a.getVideoData();this.ya=g.oL(a);this.V=a;var b=null,c=g.qo("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.Zn(c));this.aa=b;this.A={Bb:{}};this.C={Bb:{}};this.M=[];this.O={};this.Z={};this.J=!1;this.sa=g.BP(this.T,this.V);this.za=!!this.T.captionTracks.length;this.Aa=!!this.T.Uj;this.ea="3"==this.w.controlsType;b=a.app.B;c=!(!b||!b.Ml());this.wa=!(!b||!b.gi());this.B=this.ea&&c&&!this.sa;this.H=!this.B&&this.ea&&this.wa&&this.sa;this.u=this.F=this.G=this.U=this.oa=
null;this.da=new z4(this.w);g.B(this,this.da);c=b=this.o=null;this.B||(b=new g.Mn(this.bC,void 0,this),g.B(this,b),c=new g.L(this.SN,2E3,this),g.B(this,c));this.na=b;this.ha=c;this.S=new g.rr(this);g.B(this,this.S);this.B||this.S.L(a,"resize",this.du);this.S.L(a,"onPlaybackAudioChange",this.ZJ);this.S.L(a,g.VD("captions"),this.wG,this);this.S.L(a,"crx_captions",this.xG,this);A4(this,B4(this,"display-settings")||{})},D4=function(a){if(1==a.w.ug||1==a.T.ug||"alwayson"==g.HB(a.T,"yt:cc"))return!0;
if(2==a.w.ug){var b=B4(a,"module-enabled");if(null!=b)return!!b}if(a.T.captionTracks.length)var c=a.player.getAudioTrack().Up;return"ON"==c||"on"==g.HB(a.T,"yt:cc")},E4=function(a,b){if(a.o&&(void 0===b||!b)||!a.T.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.Wm||"FORCED_ON"==c.Up},G4=function(a,b){if(a.u){if(a.F&&a.F.o)return a.F.o;
var c=b;c||(c=a.Aa?!1:a.za?!1:!0);c=J3(a.u.u,c);for(var d=[a.T.captionsLanguagePreference,a.w.captionsLanguagePreference,g.HB(a.T,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(I3(c[f])==d[e])return c[f];return a.F&&a.F.gq?a.F.gq:(d=c.find(function(k){return k.isDefault}))?d:c[0]||F4(a)}return null},F4=function(a){return a.F&&a.F.Wm},H4=function(a){var b=F4(a);
return!!b&&a.o==b},Gra=function(a,b){for(var c=a.V.app.B.eb().textTracks,d=a.o.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},J4=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.J=c,a.J&&I4(a,"module-enabled",!!b));a.o=b;E4(a)&&(a.o=F4(a));a.load()},Hra=function(a,b){var c=a.ya.getVideoContentRect(!0).height;
if(!c)return null;var d=a.ya.getPlayerSize();switch(null!=b.params.aj?b.params.aj:1<b.o.length?1:0){case 1:return new r4(b,a.A,a.C,c,d.width,d.height,a.w.experiments);case 2:return new w4(b,a.A,a.C,c,d.width,d.height,a.w.experiments);default:return new V3(b,a.A,a.C,c,d.width,d.height,a.w.experiments)}},A4=function(a,b,c){var d=K4.Bb;
a.A={};g.Ma(a.A,K4);a.A.Bb={};g.Ma(a.A.Bb,d);a.C={Bb:{}};var e=b.backgroundOverride?a.C:a.A,f=b.background||d.background;n4.test(f);e.Bb.background=f;e=b.colorOverride?a.C:a.A;f=b.color||d.color;n4.test(f);e.Bb.color=f;e=b.windowColorOverride?a.C:a.A;f=b.windowColor||K4.windowColor;n4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.C:a.A;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Bb.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.C:a.A;f=b.fontSizeIncrement;null==f&&(f=d.fontSizeIncrement);
e.Bb.fontSizeIncrement=f;f=b.fontStyleOverride?a.C:a.A;e=b.fontStyle;null==e&&(e=d.bold&&d.Je?3:d.bold?1:d.Je?2:0);f=f.Bb;switch(e){case 1:f.bold=!0;delete f.Je;break;case 2:delete f.bold;f.Je=!0;break;case 3:f.bold=!0;f.Je=!0;break;default:delete f.bold,delete f.Je}e=b.textOpacityOverride?a.C:a.A;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Bb.textOpacity=f;e=b.windowOpacityOverride?a.C:a.A;f=b.windowOpacity;null==f&&(f=K4.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?a.C:a.A;f=b.charEdgeStyle;
null==f&&(f=d.charEdgeStyle);e.Bb.charEdgeStyle=f;e=b.fontFamilyOverride?a.C:a.A;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Bb.fontFamily=f;a.loaded&&a.du();c&&I4(a,"display-settings",b)},Jra=function(a,b){if(b&&!a.G){var c=Vqa({Od:0,
lang:"en"});a.G=[c,new R3(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.FL(a.player,a.G)}else!b&&a.G&&(Ira(a,a.G),a.G=null)},Ira=function(a,b){g.AT(a.player.app,b,void 0);
(0,g.y)(b,function(c){g.$a(this.M,c)},a);
g.Nn(a.na)},B4=function(a,b){if(!a.aa)return null;
try{var c=a.aa.get(b)}catch(d){a.aa.remove(b)}return c},I4=function(a,b,c){if(a.aa)try{a.aa.set(b,c)}catch(d){}};
g.mC.prototype.Vj=g.ca(12,function(){for(var a=g.Cd(document,"track",void 0,this.o),b=0;b<a.length;b++)g.Vd(a[b])});
g.mR.prototype.Vj=g.ca(11,function(){this.o.Vj()});
g.mC.prototype.Ml=g.ca(10,function(){return!!this.o.textTracks});
g.mR.prototype.Ml=g.ca(9,function(){return this.o.Ml()});
g.mC.prototype.Qj=g.ca(8,function(a){for(var b=0;b<a.length;b++)this.o.appendChild(a[b])});
g.mR.prototype.Qj=g.ca(7,function(a){this.o.Qj(a)});
g.dC.prototype.gi=g.ca(6,function(){});
g.mC.prototype.gi=g.ca(5,function(){return!(!this.o.textTracks||!this.o.textTracks.addEventListener)});
g.mR.prototype.gi=g.ca(4,function(){return this.o.gi()});
g.nz.prototype.Or=g.ca(2,function(a){return a?this.toString()==a.toString():!1});
g.nt.prototype.jn=g.ca(1,function(a){return(a=this.Of(a))?a.o:0});
g.Hy.prototype.jn=g.ca(0,function(){return 0});
var Era=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,n4=/^#(?:[0-9a-f]{3}){1,2}$/i;g.r(L3,g.A);L3.prototype.GA=function(){return!1};
L3.prototype.Y=function(){this.dh();g.A.prototype.Y.call(this)};
g.r(M3,L3);M3.prototype.Fr=function(a,b,c){b=this.mk(a,b);var d=(0,g.x)(function(e){this.o=null;c(e.responseText,a)},this);
this.dh();this.o=g.Ip(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
M3.prototype.Gr=function(a){if(this.w)for(var b=g.p(this.w.captionTracks),c=b.next();!c.done;c=b.next())K3(this.u,c.value);a()};
M3.prototype.mk=function(a,b){var c=a.G,d={fmt:b};if("srv3"==b||"3"==b||"json3"==b)g.fl()?Object.assign(d,{xorb:2,xobt:1,xovt:1}):Object.assign(d,{xorb:2,xobt:3,xovt:3});a.o&&(d.tlang=I3(a));return g.pp(c,d)};
M3.prototype.dh=function(){this.o&&this.o.abort()};
N3.prototype.contains=function(a){a=g.kb(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
N3.prototype.length=function(){return this.segments.length/2};
g.r(O3,g.A);g.h=O3.prototype;g.h.Y=function(){g.A.prototype.Y.call(this);this.u&&this.u.cancel()};
g.h.Py=function(){Qqa(this,this.w.getCurrentTime())};
g.h.reset=function(){this.B=new N3;this.u&&(this.u.cancel(),this.u=null)};
g.h.Ux=function(){var a;if(a=null!==this.o)a=this.o,a=a.o.eg(a);!a||this.u||this.o&&30<this.o.startTime-this.w.getCurrentTime()||(a=this.o,a=a.o.dj(a),a.o[0].duration?(this.B.contains(a.o[0].u)||Rqa(this,a),this.o=g.Qa(a.o)):!g.Q(this.O.experiments,"force_caption_seek_for_live_killswitch")&&this.o&&this.o.B&&this.o.B+this.w.Ab()<this.w.getCurrentTime()&&Qqa(this,this.w.getCurrentTime()));this.G.start()};
g.h.oM=function(a){var b=!(this.C?a.response:a.responseText)||400<=a.status,c=g.My(a);c?(a=g.oy(this.A,this.M,{}),b=this.A,g.ky(b.u,a,c),b.requestId=a.get("req_id"),Rqa(this,this.A)):(b||null===this.F||(c=this.A.o[0],this.C?this.F(a.response,1E3*(c.startTime+this.w.Ab())):this.F(a.responseText,1E3*(c.startTime+this.w.Ab()))),this.u=this.A=null)};
g.r(P3,L3);g.h=P3.prototype;g.h.Fr=function(a,b,c){this.dh();b=Tqa(this,a.getId());b||(b=a.u,b=this.o.u?Uqa(this,b,"386"):Uqa(this,b));if(b){var d=1E3*(b.index.jn(b.index.Ge())-b.index.Wc(b.index.Ge()));this.w=new O3(new g.fy,this.F,b,function(e,f){c(e,a,f,d)},this.C||g.cv(b.info),(0,g.x)(function(){this.w&&this.w.reset();
this.A=!0},this))}};
g.h.GA=function(){var a=this.A;this.A=!1;return a};
g.h.Gr=function(a){var b;this.C?b=[new g.nz({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.nz({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.o.u?Sqa(this,"386"):Sqa(this);b=g.p(b);for(var c=b.next();!c.done;c=b.next())K3(this.u,c.value);a()};
g.h.dh=function(){this.w&&(this.w.dispose(),this.w=null)};
g.h.mk=function(){return""};
g.r(Q3,L3);Q3.prototype.Fr=function(a,b,c){b=this.mk(a,b);var d=(0,g.x)(function(e){this.o=null;c(e.responseText,a)},this);
this.dh();this.o=g.Ip(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
Q3.prototype.Gr=function(a){var b=this.A,c={type:"list",tlangs:1,v:this.w,vssids:1};this.C&&(c.asrs=1);b=g.pp(b,c);c=(0,g.x)(function(d){this.o=null;if((d=d.responseXML)&&d.firstChild){for(var e=g.p(d.getElementsByTagName("track")),f=e.next();!f.done;f=e.next()){var k=f.value;f=k.getAttribute("lang_code");var l=k.getAttribute("lang_translated"),m=k.getAttribute("name"),n=k.getAttribute("kind"),q=k.getAttribute("id"),t="true"==k.getAttribute("lang_default"),u="true"==k.getAttribute("cantran");k=k.getAttribute("vss_id");
K3(this.u,new g.nz({languageCode:f,languageName:l,name:m,kind:n,id:q,is_servable:!0,is_translateable:u,vss_id:k,is_default:t}))}d=d.getElementsByTagName("target");e=d.length;for(f=0;f<e;f++)l=d[f].getAttribute("lang_code"),m=d[f].getAttribute("lang_translated"),n=d[f].getAttribute("lang_original"),q=d[f].getAttribute("id"),t="true"==d[f].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,id:q,isDefault:t},this.F[l.languageCode]=l.languageName,this.B.push(l)}a()},this);
this.dh();this.o=g.Ip(b,{format:"RAW",onSuccess:c,withCredentials:!0})};
Q3.prototype.mk=function(a,b){var c=this.A,d={v:this.w,type:"track",lang:a.u,name:a.getName(),kind:a.A,fmt:b};a.o&&(d.tlang=I3(a));return c=g.pp(c,d)};
Q3.prototype.dh=function(){this.o&&this.o.abort()};var Xqa=["left","right","center","justify"];var K4={windowColor:"#080808",windowOpacity:0,textAlign:2,Gf:7,Ke:50,mg:100,Bb:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.r(R3,g.SD);R3.prototype.toString=function(){return g.SD.prototype.toString.call(this)};g.r(S3,g.SD);S3.prototype.toString=function(){return g.SD.prototype.toString.call(this)};
var U3=0;g.r(V3,g.U);g.h=V3.prototype;g.h.RH=function(a,b){var c=g.Hh(this.element,this.element.parentElement);this.oa=a-c.x;this.sa=b-c.y;g.J(this.element,"ytp-dragging")};
g.h.QH=function(a,b){var c=g.Kh(this.element),d=a-this.oa-.02*this.Ka,e=b-this.sa-.02*this.Ga,f=(d+c.width/2)/this.aa*3;f=Math.floor(g.nd(f,0,2));var k=(e+c.height/2)/this.wa*3;k=Math.floor(g.nd(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.aa;d=100*g.nd(d,0,1);c=(e+k/2*c.height)/this.wa;c=100*g.nd(c,0,1);this.w.params.Gf=l;this.w.params.mg=c;this.w.params.Ke=d;this.u.Gf=l;this.u.mg=c;this.u.Ke=d;this.fB()};
g.h.PH=function(){g.on(this.element,"ytp-dragging")};
g.h.fB=function(){this.ci(this.C)};
g.h.ci=function(a){var b=Math.min(this.Fw(),this.aa),c=this.Ew(),d="";3==this.w.params.Od&&(d="rotate(180deg)");g.qh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Lp(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.u.Ke+2;d=this.u.Gf;switch(d){case 0:case 3:case 6:a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.B.offsetWidth;
b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.u.mg+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.qh(this.element,a)};
g.h.Lp=function(a){var b;for(b=0;b<a.length&&a[b]==this.C[b];b++);if(this.S||this.C.length>b)b=0,this.S=!1,this.C=[],this.F=this.U=this.V=null,g.Td(this.B);for(;b<a.length;b++)ara(this,a[b])};
g.h.Fw=function(){return 0};
g.h.Ew=function(){return 0};
g.h.toString=function(){return g.U.prototype.toString.call(this)};bra.prototype.B=function(){};X3.prototype.clear=function(){this.A=this.u=this.mode=0;this.o=[];this.reset()};
X3.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var cra=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];Y3.prototype.set=function(a){this.o=a};
Y3.prototype.get=function(){return this.o};
Z3.prototype.clear=function(){this.o=0};
Z3.prototype.update=function(){this.o=2==this.o?1:0};
Z3.prototype.matches=function(a,b){return 0!=this.o&&a==this.w&&b==this.u};
$3.prototype.xg=function(a){this.le=a.le;this.timestamp=a.timestamp};
$3.prototype.reset=function(){this.timestamp=this.le=0};
a4.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.w[b][c].timestamp=a};
a4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.w[b][c];a=0==d.le?a+"_":a+String.fromCharCode(d.le)}a+="\n"}return a};
a4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.w[b][c].reset();this.A=a;this.o=0;this.u=this.row=1};
var hra=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],ira=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],jra=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],kra=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];g4.prototype.reset=function(a,b){this.B=b;this.style.set(2);this.u=this.C;this.w=this.F;this.o=this.u;var c=(a<<2)+(b<<1);this.C.reset(c);this.F.reset(c);this.G.reset((a<<2)+(b<<1)+1)};
W3.prototype.reset=function(a){this.B=a;this.o.clear();this.A=this.w;this.w.reset(a,0);this.C.reset(a,1)};g.r(i4,g.A);i4.prototype.reset=function(){};g.r(j4,i4);j4.prototype.reset=function(){this.G={};this.u=this.o=null;this.F=!0};
j4.prototype.w=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.p(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.p(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.A,l={},m=c.getAttribute("p");m&&g.Ma(l,this.A[m]);m=l4(c,"b");null!=m&&(l.bold=
m);m=l4(c,"i");null!=m&&(l.Je=m);m=l4(c,"u");null!=m&&(l.underline=m);m=m4(c,"et");null!=m&&(l.charEdgeStyle=m);m=m4(c,"of");null!=m&&(l.offset=m);m=o4(c,"bc");null!=m&&(l.background=m);m=o4(c,"ec");null!=m&&(l.Xp=m);m=o4(c,"fc");null!=m&&(l.color=m);m=m4(c,"fs");null!=m&&0!=m&&(l.fontFamily=m);m=k4(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=k4(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);m=k4(c,"fo");void 0!=m&&(l.textOpacity=m/255);m=m4(c,"rb");null!=m&&10!=m&&0!=m&&(l.Mb=10<m?m-1:m);
c=m4(c,"hg");null!=c&&(l.nx=c);k[d]=l;break;case "ws":d=c.getAttribute("id");this.M[d]=rra(this,c);break;case "wp":d=c.getAttribute("id"),this.H[d]=sra(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.p(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.o=tra(this,d,e,!1);g.B(this,this.o);(d=this.G[this.o.id])&&d.end>this.o.start&&(d.end=this.o.start);this.G[this.o.id]=this.o;c.push(this.o);break;case "p":var n=e;k=[];l=d.getAttribute("w")||this.B;
m=!!l4(d,"a");n=(k4(d,"t")||0)+n;var q=k4(d,"d")||5E3;m||(!this.F&&this.u&&this.u.windowId==l&&this.u.end>n&&(this.u.end=n),this.u&&"\n"==this.u.text&&(this.u.text=""));var t=m?6:5,u=this.A[d.getAttribute("p")],z=[].concat(g.ea(d.childNodes));z.length&&(this.F=null!=d.getAttribute("d"));for(var C=0;C<z.length;C++){var D=z[C],G=void 0;0<C&&(m=!0);var F=void 0;1==D.nodeType&&(F=D);if(F&&"s"==F.tagName){if((D=this.A[F.getAttribute("p")])&&D.Mb&&(1==D.Mb?(D=z.slice(C,C+4),4==D.length&&(G=qra(n,q,l,m,
t,D,this.A),C+=3)):G=qra(n,q,l,m,t,[F],this.A)),!G){var E=F;G=n;F=q;D=l;var M=m,X=t,bb=E.textContent?E.textContent:"",uc=this.A[E.getAttribute("p")];E=k4(E,"t")||0;G=new R3(G+E,F-E,X,D,bb,M,uc)}}else G=new R3(n,q,t,l,D.textContent||"",m,u);k.push(G);this.u=G}if(0<k.length)for(k[0].windowId==this.B&&(this.o=tra(this,d,e,!0),g.B(this,this.o),c.push(this.o)),d=g.p(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.o.id,T3(this.o,k),c.push(k)}e=c}else e=[];return e};var Kra=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.r(p4,i4);p4.prototype.reset=function(){this.u.clear()};
p4.prototype.w=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens)for(var d=0,e=g.p(c.pens),f=e.next();!f.done;f=e.next()){f=f.value;var k={},l=f.pParentId;l&&Object.assign(k,this.o.get(l));f.bAttr&&(k.bold=!0);f.iAttr&&(k.Je=!0);f.uAttr&&(k.underline=!0);l=f.ofOffset;null!=l&&(k.offset=l);f.szPenSize&&(k.fontSizeIncrement=f.szPenSize/100-1);l=f.etEdgeType;null!=l&&(k.charEdgeStyle=l);void 0!=f.ecEdgeColor&&(k.Xp=q4(f.ecEdgeColor));l=f.fsFontStyle;null!=l&&0!==l&&(k.fontFamily=l);void 0!=
f.fcForeColor&&(k.color=q4(f.fcForeColor));void 0!=f.foForeAlpha&&(k.textOpacity=f.foForeAlpha/255);void 0!=f.bcBackColor&&(k.background=q4(f.bcBackColor));void 0!=f.boBackAlpha&&(k.backgroundOpacity=f.boBackAlpha/255);(l=f.rbRuby)&&10!==l&&(k.Mb=10<l?l-1:l,k.Re=Kra.get(k.Mb));f.hgHorizGroup&&(k.nx=f.hgHorizGroup);this.o.set(d++,k)}if(c.wsWinStyles)for(d=0,e=g.p(c.wsWinStyles),f=e.next();!f.done;f=e.next())f=f.value,k={},(l=f.wsParentId)?Object.assign(k,this.B.get(l)):Object.assign(k,this.C),void 0!=
f.mhModeHint&&(k.aj=f.mhModeHint),void 0!=f.juJustifCode&&(k.textAlign=f.juJustifCode),void 0!=f.pdPrintDir&&(k.Od=f.pdPrintDir),void 0!=f.sdScrollDir&&(k.Tt=f.sdScrollDir),void 0!=f.wfcWinFillColor&&(k.windowColor=q4(f.wfcWinFillColor)),void 0!=f.wfoWinFillAlpha&&(k.windowOpacity=f.wfoWinFillAlpha/255),this.B.set(d++,k);if(c.wpWinPositions)for(d=0,e=g.p(c.wpWinPositions),f=e.next();!f.done;f=e.next())f=f.value,k={},(l=f.wpParentId)&&Object.assign(k,this.A.get(l)),l=k,void 0!=f.ahHorPos&&(l.Ke=f.ahHorPos),
void 0!=f.apPoint&&(l.Gf=f.apPoint),void 0!=f.avVerPos&&(l.mg=f.avVerPos),void 0!=f.ccCols&&(l.vg=f.ccCols),void 0!=f.rcRows&&(l.lg=f.rcRows),this.A.set(d++,k);if(c.events)for(d=[],c=g.p(c.events),e=c.next();!e.done;e=c.next()){var m=e.value;e=(m.tStartMs||0)+b;f=m.dDurationMs||0;if(m.id)k=String(m.id),e=ura(this,m,e,f,k),d.push(e),this.u.set(k,e);else{m.wWinId?k=m.wWinId.toString():(k="_"+U3++,l=ura(this,m,e,f,k),d.push(l),this.u.set(k,l));0===f&&(f=5E3);l=this.u.get(k);var n=!!m.aAppend,q=n?6:5,
t=m.segs,u=null;m.pPenId&&(u=this.o.get(m.pPenId));for(m=0;m<t.length;m++){var z=t[m],C=z.utf8;if(C){var D=z.tOffsetMs||0,G=null;z.pPenId&&(G=this.o.get(z.pPenId));if(2===(null!=l.params.aj?l.params.aj:1<l.o.length?1:0)&&n&&"\n"===C)continue;if(z=G&&1===G.Mb)if(z=m,z+3>=t.length||!t[z+1].pPenId||!t[z+2].pPenId||!t[z+3].pPenId)z=!1;else{var F=t[z+1].pPenId;(F=this.o.get(F))&&F.Mb&&2==F.Mb?(F=t[z+2].pPenId,F=this.o.get(F),!F||!F.Mb||3>F.Mb?z=!1:(F=t[z+3].pPenId,z=(F=this.o.get(F))&&F.Mb&&2==F.Mb?!0:
!1)):z=!1}if(z){D=t[m+1].utf8;z=t[m+3].utf8;F=t[m+2].utf8;var E=this.o.get(t[m+2].pPenId);C=pra(C,D,F,z,E);n=new R3(e,f,q,k,C,n,G);m+=3}else n=new R3(e+D,f-D,q,l.id,C,n,G||u);n&&(d.push(n),T3(l,n))}n=!0}}}else d=[];return d};g.r(r4,V3);r4.prototype.Lp=function(a){var b=this.w.o;V3.prototype.Lp.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.o==e)var d=f;else{d={};g.Ma(d,c.o);g.Ma(d,Lra);var e=c.o;var f=d}ara(this,c,d)}};
var Lra={sF:!0};g.r(s4,bra);s4.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+U3++;c=c/1E3-this.F;d=d/1E3-this.F;a=new S3(c,d-c,5,f,{textAlign:0,Gf:0,Ke:2.5*b,mg:5.33*a});e=new R3(c,d-c,5,f,e);this.w.push(a);this.w.push(e)}};
g.r(v4,i4);v4.prototype.w=function(a){a=new s4(a,a.byteLength,this.u);if(vra(a)){for(;a.o<a.u.byteLength;)for(0==a.version?a.A=u4(a)*(1E3/45):1==a.version&&(a.A=4294967296*u4(a)+u4(a)),a.C=t4(a);0<a.C;a.C--){var b=t4(a),c=t4(a),d=t4(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.o,b.o.push({time:a.A,type:this.track,Gv:c,Hv:d,order:b.o.length}))}gra(this.o,a);return a.w}return[]};
v4.prototype.reset=function(){this.o.clear()};g.r(w4,V3);g.h=w4.prototype;g.h.fB=function(){g.Rn(this.ea)};
g.h.tM=function(){g.on(this.element,"ytp-rollup-mode");this.ci(this.Aa,!0)};
g.h.Ew=function(){return this.A?this.J:this.H};
g.h.Fw=function(){return this.A?this.H:this.J};
g.h.ci=function(a,b){this.Aa=a;if(this.w.params.lg){for(var c=0,d=0;d<this.C.length&&c<a.length;d++)this.C[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.C.concat(a.slice(c)));this.ya=this.J;this.H=this.J=0;V3.prototype.ci.call(this,a);Bra(this,b);V3.prototype.ci.call(this,a)}else V3.prototype.ci.call(this,a)};g.r(x4,i4);
x4.prototype.w=function(a,b){for(var c=[],d=a.split(Mra),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!Nra.test(f)){var l=L4.exec(f);if(l&&4<=l.length){var m=y4(l[1]),n=y4(l[2])-m;m+=k;var q,t=q=void 0,u=void 0,z=void 0,C=(l=l[3])?l.split(" "):[];l={textAlign:2};C=g.p(C);for(var D=C.next();!D.done;D=C.next())if(D=D.value.split(":"),2==D.length){var G=D[1];switch(D[0]){case "line":D=G.split(",");D[0].endsWith("%")&&(z=D[0],l.mg=Number.parseInt(z,10),2==D.length&&(u=D[1].trim()));break;case "position":D=G.split(",");
t=D[0];l.Ke=Number.parseInt(t,10);2==D.length&&(q=D[1].trim());break;case "align":switch(G){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}z||(l.mg=100,u||(u="end"));if(!t)switch(l.textAlign){case 0:l.Ke=0;break;case 1:l.Ke=100;break;default:l.Ke=50}t=0;switch(u){case "center":t+=3;break;case "end":t+=6;break;default:t+=0}switch(q){case "line-left":t+=0;break;case "center":t+=1;break;case "line-right":t+=2;break;default:switch(l.textAlign){case 0:t+=
0;break;case 2:t+=1;break;case 1:t+=2}}l.Gf=0>t||8<t?7:t;q=l;f=f.substring(L4.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");t=q;q=f;f={};if(0>q.indexOf("<")&&0>q.indexOf("&"))k=Dra(m,n,5,t),n=new R3(m,n,5,k.id,q,!1,g.Vb(f)?void 0:f),c.push(k),c.push(n),T3(k,n);else for(u=q.split(Ora),1==u.length?(q=5,t=Dra(m,n,q,t)):(z=q=6,t=Object.assign({vg:32},t),t=new S3(m,n,z,"_"+U3++,t)),c.push(t),z=m,l=0;l<u.length;l++)C=u[l],0==l%2?(D=g.C1("<html>"+C+"</html>"),D.getElementsByTagName("parsererror").length?
(G=D.createElement("span"),G.appendChild(D.createTextNode(C))):G=D.firstChild,Cra(this,z,n-(z-m),q,t,0<l,G,f,c)):z=y4(C)+k}L4.lastIndex=0}}return c};
var Nra=/^NOTE/,Mra=/(?:\r\n|\r|\n){2,}/,L4=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Ora=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.r(z4,g.A);z4.prototype.clear=function(){this.o&&this.o.dispose();this.o=null};
z4.prototype.reset=function(){this.o&&this.o.reset()};
z4.prototype.Y=function(){this.clear();g.A.prototype.Y.call(this)};g.r(C4,g.zP);g.h=C4.prototype;g.h.Y=function(){if(this.B||this.H){var a=this.V.app.B;a&&a.Vj()}else Jra(this,!1);g.zP.prototype.Y.call(this)};
g.h.load=function(){g.zP.prototype.load.call(this);var a=!g.Q(this.w.experiments,"web_player_captions_track_list_changed_killswitch");this.F=this.player.getAudioTrack();if(this.u){if(this.o){this.da.clear();if(this.B)Gra(this,!0);else if(3!=this.player.getPresentingPlayerType()){var b=g.Q(this.w.experiments,"html5_enable_json_subtitle")?"json3":"srv3";this.u.Fr(this.o,b,(0,g.x)(this.bN,this))}!a||this.B||this.H||H4(this)||this.player.la("captionschanged",H3(this.o))}a||(this.o&&!H4(this)?this.player.la("captionschanged",
H3(this.o)):this.player.la("onCaptionsTrackListChanged"))}else this.sa?b=new P3(this.T.ma,this.player):this.za?b=new M3(this.w,this.T,this.player.getAudioTrack()):b=new Q3(this.T.Uj,this.T.videoId,this.T.captionsLanguagePreference||this.w.captionsLanguagePreference||g.HB(this.T,"yt:cc_default_lang")||this.w.Cc,this.T.Sp,this.w),this.u=b,g.B(this,this.u),b.Gr((0,g.x)(this.aN,this))};
g.h.unload=function(){this.B&&this.o?Gra(this,!1):(this.ha&&g.Sn(this.ha),g.QQ(this.player.app,"captions",void 0),this.M=[],this.u&&this.u.dh(),this.da.clear(),this.G&&g.FL(this.player,this.G),this.du());g.zP.prototype.unload.call(this);var a=g.T(this.player.app);a&&g.GI(a.B);this.player.la("captionschanged",{})};
g.h.create=function(){(this.ea?this.B||this.H:E4(this)||D4(this))&&this.load()};
g.h.aN=function(){var a;this.J||D4(this)?a=G4(this,this.J):E4(this)&&(a=F4(this));if(this.B||this.H){for(var b=J3(this.u.u,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.oz(e),srclang:I3(e),id:e.toString()};this.H||(f.src=this.u.mk(e,"vtt"));e==a&&(f["default"]=1);c.push(g.Pd("TRACK",f))}a=this.V.app.B;a.Qj(c);c=a.eb();this.wa&&this.S.L(c.textTracks,"change",this.cN)}else!this.o&&a&&J4(this,a),this.player.la("onCaptionsTrackListChanged"),this.player.la("onApiChange")};
g.h.cN=function(){for(var a=this.V.app.B.eb().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=a[c].id;var d=J3(this.u.u,!0);for(var e=0;e<d.length;e++)if(d[e].toString()==b){b=d[e];break a}b=null}(this.loaded?this.o:null)!=b&&J4(this,b,!0)};
g.h.GO=function(){!this.o&&this.B||this.unload()};
g.h.bN=function(a,b,c,d){if(a){this.u.GA()&&(this.M=[],g.QQ(this.V.app,"captions",void 0),g.Nn(this.na),this.da.reset());var e=this.da;c=c||0;d=d||0;if("string"!==typeof a){var f=new DataView(a);if(8<=f.byteLength&&1718909296==f.getUint32(4)&&(f=g.Ot(f,0,1835295092),a=a.slice(f.dataOffset,f.dataOffset+f.size),!wra(a))){a=new Uint8Array(a);f=[];for(var k=0,l=0;k<a.length;){var m=a[k++];if(128>m)f[l++]=String.fromCharCode(m);else if(191<m&&224>m){var n=a[k++];f[l++]=String.fromCharCode((m&31)<<6|n&
63)}else if(239<m&&365>m){n=a[k++];var q=a[k++],t=a[k++];m=((m&7)<<18|(n&63)<<12|(q&63)<<6|t&63)-65536;f[l++]=String.fromCharCode(55296+(m>>10));f[l++]=String.fromCharCode(56320+(m&1023))}else n=a[k++],q=a[k++],f[l++]=String.fromCharCode((m&15)<<12|(n&63)<<6|q&63)}a=f.join("")}}if(a)try{if("string"!==typeof a){var u=a,z=d;if(!wra(u))throw Error("Invalid binary caption track data");e.o||(e.o=new v4(z,b));var C=e.o.w(u,c)}else{if("WEBVTT"==a.substring(0,6))b=a,e.o||(e.o=new x4),z=e.o.w(b,c),.01>Math.random()&&
g.Co(Error("Deprecated subtitles format in web player: WebVTT")),u=z;else b:{z=a;if(g.Q(e.u.experiments,"html5_enable_json_subtitle")&&"{"===z[0])try{e.o||(e.o=new p4(Fra(b)));u=e.o.w(z,c);break b}catch(bb){g.O(bb);u=[];break b}var D=g.C1(z);if(!D||!D.firstChild){var G=Error("Invalid caption track data");G.params=z;throw G;}if("timedtext"==D.firstChild.tagName){if(3==parseInt(D.firstChild.getAttribute("format"),10)){e.o||(e.o=new j4(Fra(b),e.u));u=e.o.w(D,c);break b}var F=Error("Unsupported subtitles format in web player (Format2)");
F.params=z;throw F;}if("transcript"==D.firstChild.tagName){var E=Error("Unsupported subtitles format in web player (Format1)");E.params=z;throw E;}var M=Error("Invalid caption track data");M.params=z;throw M;}C=u}var X=C}catch(bb){g.O(bb),e.clear(),X=[]}else X=[];g.FL(this.player,X);!this.J||this.H||H4(this)||g.Jx(this.w)||g.Kx(this.w)||(g.Sn(this.ha),X=Vqa({Gf:0,Ke:5,mg:5,lg:2,textAlign:0,Od:0,lang:"en"}),this.U=[X],e=["Click "," for settings"],this.oa||(C=new g.BC(g.BM()),g.B(this,C),this.oa=C.element),
C=X.end-X.start,(b=g.oz(this.o))&&this.U.push(new R3(X.start,C,0,X.id,b)),this.U.push(new R3(X.start,C,0,X.id,e[0]),new R3(X.start,C,0,X.id,this.oa,!0),new R3(X.start,C,0,X.id,e[1],!0)),g.FL(this.player,this.U),g.Qn(this.ha));!this.J||this.H||H4(this)||(I4(this,"module-enabled",!0),this.F&&(this.F.o=this.o),(X=g.T(this.player.app))&&g.GI(X.B));this.J=!1}};
g.h.wG=function(a){this.M.push(a);g.Nn(this.na)};
g.h.xG=function(a){g.$a(this.M,a);this.u instanceof P3&&this.u.C&&g.AT(this.player.app,[a],void 0);g.Nn(this.na)};
g.h.KN=function(a){if(a instanceof S3){var b=this.O[a.id];b&&b.w!=a&&(b.dispose(),delete this.O[a.id],b=null);b||(b=Hra(this,a))&&(this.O[a.id]=b)}else b=a.windowId,this.Z[b]||(this.Z[b]=[]),this.Z[b].push(a)};
g.h.SN=function(){Ira(this,this.U);this.U=null};
g.h.bC=function(){this.na.stop();g.Wb(this.Z);this.M.sort(g.UD);var a=this.M;if(this.G){var b=(0,g.Wd)(a,function(c){return-1==this.G.indexOf(c)},this);
b.length&&(a=b)}(0,g.y)(a,this.KN,this);g.Ib(this.O,function(c,d){this.Z[d]?(c.element.parentNode||g.JL(this.player,c.element,4),c.ci(this.Z[d])):(c.dispose(),delete this.O[d])},this)};
g.h.ZN=function(){A4(this,{},!0);g.Q(this.w.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.la("captionssettingschanged")};
g.h.IE=function(){var a=K4.Bb;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Je?3:a.bold?1:a.Je?2:0,textOpacity:a.textOpacity,windowColor:K4.windowColor,windowOpacity:K4.windowOpacity};var b=B4(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.gC=function(a,b){var c={};g.Ma(c,B4(this,"display-settings"));g.Ma(c,a);A4(this,c,b);this.player.la("captionssettingschanged")};
g.h.du=function(){!this.B&&this.loaded&&(g.Ib(this.O,function(a,b){a.dispose();delete this.O[b]},this),this.bC())};
g.h.Ic=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.nd(b,-2,4);this.gC({fontSizeIncrement:c});return c;case "reload":b&&!this.B&&J4(this,this.o,!0);break;case "stickyLoading":void 0!=b&&this.w.Cb&&I4(this,"module-enabled",!!b);break;case "track":if(!this.u)return{};if(b){if(this.B)break;if(!g.Ia(b))break;if(g.Vb(b)){J4(this,null,!0);break}for(var d=J3(this.u.u,!0),e=0;e<d.length;e++){var f=d[e];f.u!=b.languageCode||c&&f.w!=b.languageName||(c=b.translationLanguage?Oqa(f,b.translationLanguage):
f)}!c||c==this.o&&this.loaded||J4(this,c,!0)}else return this.loaded&&this.o&&!H4(this)?H3(this.o):{};return"";case "tracklist":return this.u?(0,g.Fc)(J3(this.u.u,!(!b||!b.includeAsr)),function(k){return H3(k)}):[];
case "translationLanguages":return this.u?this.u.B.map(function(k){return Object.assign({},k)}):[];
case "sampleSubtitles":this.B||void 0==b||Jra(this,!!b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.w.Cb&&a.push("stickyLoading");return a};
g.h.vG=function(){var a=this.o;return a?{cc:a.C}:{}};
g.h.zO=function(){this.loaded&&this.o&&!H4(this)?(I4(this,"module-enabled",!1),this.unload(),E4(this,!0)&&J4(this,F4(this),!1)):J4(this,H4(this)||!this.o?G4(this,!0):this.o,!0)};
g.h.ZJ=function(){var a=H4(this);E4(this,a)?J4(this,this.player.getAudioTrack().Wm,!1):this.T.captionTracks.length&&(this.loaded&&this.unload(),(this.ea?this.B||this.H:E4(this)||D4(this))&&(a?J4(this,G4(this),!1):this.load()))};g.OP.captions=C4;})(_yt_player);
